version: 0.2

env:
  variables:
    ECR_REPO_NAME: 'sortlink'
    AWS_ACCOUNT_ID: '905417994528'
    AWS_DEFAULT_REGION: 'us-east-1'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g yarn
      - yarn install --frozen-lockfile

  pre_build:
    commands:
      - yarn test || true
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}-$(date +%Y%m%d%H%M%S)

  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${ECR_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}

artifacts:
  files:
    - imagedefinitions.json
