name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted  # Hoặc ubuntu-latest nếu dùng GitHub-hosted runner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'  # Chỉ định rõ version 22.x
        cache: 'yarn'
    
    - name: Install Yarn
      run: |
        npm install --global yarn
        echo "::add-path::$(npm bin -g)"
    
    - run: yarn install --frozen-lockfile
    - run: yarn prisma generate
    - run: yarn build --if-present
    - run: yarn test
